[build-system]
requires = ["setuptools>=64", "setuptools-scm>=6.4", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
root = "."
write_to = "src/karaboWorkshopPipelines/_version.py"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
KaraboWorkshopPipelines = ["data/*.*"]

[tool.isort]
combine_as_imports = true
include_trailing_comma = false
# 4 - Hanging Grid, standard
multi_line_output = 4
line_length = 79
known_first_party = ["karabo", "KaraboWorkshopPipelines"]
src_paths = ["src"]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "module"
asyncio_default_test_loop_scope = "module"
asyncio_mode = "auto"

[project.entry-points."karabo.middlelayer_device"]
KaraboWorkshopPipelines = "karaboWorkshopPipelines.KaraboWorkshopPipelines:KaraboWorkshopPipelines"

[project]
license = {file = "LICENSE.md"}
dynamic = ["version"]
name = "KaraboWorkshopPipelines"
authors = [
    {name = "Andrea Parenti"},
    {name = "Gero Flucke"},
]
maintainers = [
    {name = "Gero Flucke"},
]
description = ""
readme = "README.md"
dependencies = [
]
